export const AUTH = 'AUTH';
export const LOAD_USERS = 'LOAD_USERS';
export const LOAD_REGIONS = 'LOAD_REGIONS';
export const LOAD_CONTACTS = 'LOAD_CONTACTS';
export const LOAD_RETAILERS = 'LOAD_RETAILERS';
export const LOAD_WORKSHOP = 'LOAD_WORKSHOP';
export const LOAD_PICK_LIST = 'LOAD_PICK_LIST';
export const LOAD_INCENTIVE = 'LOAD_INCENTIVE';
export const LOAD_TYPES_LIST = 'LOAD_TYPES_LIST';
export const LOAD_DISTRIBUTORS = 'LOAD_DISTRIBUTORS';
export const LOAD_FOCUSED_PRODUCTS = 'LOAD_FOCUSED_PRODUCTS';
export const LOAD_DISTRIBUTOR_CONTACTS = 'LOAD_DISTRIBUTOR_CONTACTS';
export const LOAD_DISTRIBUTOR_PRODUCT = 'LOAD_DISTRIBUTOR_PRODUCT';
export const LOAD_ROUTE_LINES = 'LOAD_ROUTE_LINES';
export const CREATE_ROUTE = 'CREATE_ROUTE';
export const CREATE_JOURNEY = 'CREATE_JOURNEY';
export const CREATE_ORDER = 'CREATE_ORDER';
export const RESET_ORDER = 'RESET_ORDER';
export const CANCEL_ORDERS = 'CANCEL_ORDERS';

export const LOAD_ACCESS_DETAILS = 'LOAD_ACCESS_DETAILS';
export const SUBMIT_JOURNEY = 'SUBMIT_JOURNEY';
export const SUBMIT_APPROVED_JOURNEY = 'SUBMIT_APPROVED_JOURNEY';

export const CREATE_RETAILER = 'CREATE_RETAILER';
export const CREATE_WORKSHOP = 'CREATE_WORKSHOP';
export const CREATE_DEALER_VISIT = 'CREATE_DEALER_VISIT';
export const CREATE_UNPLANNED_VISIT = 'CREATE_UNPLANNED_VISIT';
export const CREATE_PROMOTION = 'CREATE_PROMOTION';
export const COMPLETE_PROMOTION = 'COMPLETE_PROMOTION';
export const CREATE_LEAD = 'CREATE_LEAD';
export const CREATE_LEAD_TRIAL = 'CREATE_LEAD_TRIAL';
export const FETCH_LEAD = 'FETCH_LEAD';
export const CREATE_TASK = 'CREATE_TASK';

export const FETCH_SUBMITTED_JOURNEYS = 'FETCH_SUBMITTED_JOURNEYS';
export const FETCH_JOURNEYS = 'FETCH_JOURNEYS';
export const FETCH_GST_DETAILS = 'FETCH_GST_DETAILS';
export const LOAD_INCENTIVES = 'LOAD_INCENTIVES';
export const LOAD_USER = 'LOAD_USER';
export const LOAD_SYCN_SCHEME = 'LOAD_SYCN_SCHEME';

export const ADD_TO_CART = 'ADD_TO_CART';
export const SET_CART = 'SET_CART';
export const UPDATE_VALUE_SCHEME = 'UPDATE_VALUE_SCHEME';
export const UPDATE_TO_CART = 'UPDATE_TO_CART';
export const REMOVE_TO_CART = 'REMOVE_TO_CART';

export const UPDATE_SCHEMES = 'UPDATE_SCHEMES';

export const CHECK_IN = 'CHECK_IN';
export const CHECK_OUT = 'CHECK_OUT';

export const REMOVE_CHECK_IN_DETAIL = 'REMOVE_CHECK_IN_DETAIL';

export const LOGOUT = 'LOGOUT';
export const REQUEST = 'REQUEST';
export const SUCCESS = 'SUCCESS';
export const FAIL = 'FAIL';
export const OFFLINE = 'OFFLINE';
